# Generated by Django 5.0.4 on 2024-05-01 19:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_remove_student_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("car_name", models.CharField(max_length=50)),
                ("speed", models.IntegerField(default=50)),
            ],
        ),
        migrations.DeleteModel(
            name="Check",
        ),
    ]
